Repository skku-amang/backend, pull requests merged in 2024-10, with the labels that each got.

#51 50 generation order fix
  core/serializers/generation.py
  core/urls.py
  core/views/generation.py
Labels: 🐞 BugFix

#56 44 generation unit test code
  core/tests/__init__.py
  core/tests/test_generation.py
Labels: ✅ Test

#58 feat: add team list of specific performance api
  core/urls.py
  core/views/performance.py
Labels: ✨ Feature
